function(lotus_check_gpu_evidence report skip_detail)
  set(${skip_detail} "" PARENT_SCOPE)
  if(NOT EXISTS "${report}")
    message(FATAL_ERROR "GPU capability report is missing: ${report}")
  endif()
  file(READ "${report}" report_json)
  string(JSON count LENGTH "${report_json}" checks)
  if(count GREATER 0)
    math(EXPR last "${count} - 1")
    foreach(index RANGE 0 ${last})
      string(JSON id GET "${report_json}" checks ${index} id)
      if(id STREQUAL "renderer.gpu.frame")
        string(JSON status GET "${report_json}" checks ${index} status)
        if(status STREQUAL "pass")
          return()
        elseif(status STREQUAL "skip")
          string(JSON detail GET "${report_json}" checks ${index} detail)
          if(detail STREQUAL "")
            message(FATAL_ERROR "GPU capability SKIP has no explanation")
          endif()
          set(${skip_detail} "${detail}" PARENT_SCOPE)
          return()
        endif()
        message(FATAL_ERROR "GPU frame evidence has status '${status}'")
      endif()
    endforeach()
  endif()
  message(FATAL_ERROR "GPU capability report has no renderer.gpu.frame assertion")
endfunction()
